export const PRODUCTO_LISTAR = 'PRODUCTO_LISTAR';
export const GRUPO_PRODUCTO_LISTAR = 'GRUPO_PRODUCTO_LISTAR';
export const CATEGORIAS_GRUPOS = 'CATEGORIAS_GRUPOS';
export const ORDER_LIST = 'ORDER_LIST';
export const PRODUCTO_POST = 'PRODUCTO_POST';

